run:
	hazelnut run ./hazelnut.hzl ./stdlib.hzl

show:
	hazelnut show ./hazelnut.hzl ./stdlib.hzl

build:
	hazelnut build ./hazelnut.hzl ./stdlib.hzl

tokens:
	hazelnut tokens ./hazelnut.hzl ./stdlib.hzl

go:
	hazelnut ./hazelnut.hzl ./stdlib.hzl
