# Site settings
title: Hazelnut
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A programming language I'm working on.
baseurl: "/hazelnut/" # the subpath of your site, e.g. /blog/
github: "https://github.com/Charlesetc/hazelnut"

# Build settings
markdown: kramdown
